"""initial schema

Revision ID: 7d5619c519c1
Revises:
Create Date: 2026-09-22 12:54:44.280196

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d5619c519c1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="healthy", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('healthy', 'unreachable', 'decommissioned')", name="ck_storage_nodes_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_hash"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("data_shards", sa.SmallInteger(), nullable=False),
        sa.Column("parity_shards", sa.SmallInteger(), nullable=False),
        sa.Column("link_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("status", sa.String(), server_default="uploading", nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('uploading', 'available', 'deleted')", name="ck_files_status"
        ),
        sa.CheckConstraint("data_shards >= 1 AND parity_shards >= 1", name="ck_files_shard_counts"),
        sa.CheckConstraint("size_bytes > 0", name="ck_files_size_positive"),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_files_owner", "files", ["owner_user_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("ttl_seconds", sa.Integer(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('file_uploaded', 'link_generated', 'download_success', 'download_denied', 'file_deleted')",
            name="ck_audit_event_type",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_created_at", "audit_events", ["created_at"], unique=False)
    op.create_index("idx_audit_file", "audit_events", ["file_id"], unique=False)
    op.create_table(
        "shards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("shard_index", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('data', 'parity')", name="ck_shards_kind"),
        sa.CheckConstraint("shard_index >= 0", name="ck_shards_index_nonnegative"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["storage_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id", "shard_index", name="uq_shards_file_index"),
    )
    op.create_index("idx_shards_node", "shards", ["node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_shards_node", table_name="shards")
    op.drop_table("shards")
    op.drop_index("idx_audit_file", table_name="audit_events")
    op.drop_index("idx_audit_created_at", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("idx_files_owner", table_name="files")
    op.drop_table("files")
    op.drop_table("users")
    op.drop_table("storage_nodes")
    # ### end Alembic commands ###
